### ISSUE TITLE
new dataset

### ISSUE THREAD

**Issue by osamagharbi** [jarikorhonen/cnn-tlvqm#1]
first Thank you very much for the work you are doing!.

please can you guide me how to train the models on my dataset ?
PS: i have an MOS  range between 0 and 4.

and please what represents the values in allstdev_release. mat ?

thanks in advance.

**Comment by jarikorhonen** [comment]
The contents inside the for-loop in lines 26-36 should be modified so that it reads the paths for the files in your database and passes them as parameter to the computeCNNTLVQMfeatures function. You should also make sure that you have the mos values ​​in vector'mos' in the same order you have your files. It is probably a good idea to normalize your MOS values ​​to range 0-1 by dividing them by 4.  Also you need to change [960 540] to your resolution, and 30 to the frame rate of your video.

Allstdev only matters if you want to train your own feature extractor predicting the probabilistic scores, if you use the pre-trained model, you don't need to care about that.
